Read in a .csv file

In [81]:
#Allowing you to access files from Google Drive
from google.colab import drive
#Importing the PANDAS Library
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')
# You can comment the drive mount once the drive has been mounted, but you would have to re-mount when you log on to run the script in the future

# Specify the correct file path (modify if necessary)
file_path = '/content/drive/MyDrive/DataWrangling/CVD_V2.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [82]:
pd.read_csv(file_path)

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0,30,16,12
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0,30,0,4
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4,12,3,16
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,NaN,No,0,30,30,8
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0,8,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308852,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,25-29,168.0,81.65,29.05,No,4,30,8,0
308853,Fair,Within the past 5 years,Yes,No,No,No,No,Yes,No,Male,65-69,180.0,69.85,21.48,No,8,15,60,4
308854,Very Good,5 or more years ago,Yes,No,No,No,Yes,"Yes, but female told only during pregnancy",No,Female,30-34,157.0,61.23,24.69,Yes,4,40,8,4
308855,Very Good,Within the past year,Yes,No,No,No,No,No,No,Male,65-69,183.0,79.38,23.73,No,3,30,12,0
308856,Excellent,Within the past year,Yes,No,No,No,No,No,No,Female,45-49,160.0,81.19,31.71,No,1,5,12,1

In [83]:
df = pd.read_csv(file_path)

- Report the number of rows and columns

In [84]:
num_rows = df.shape[0]
num_columns = df.shape[1]

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 308857
Number of columns: 19

- Report the min, max, and mean of Height, Weight and BMI columns

In [110]:
#1 Height discriptive statistics
min_height = df['Height_(cm)'].min()
max_height = df['Height_(cm)'].max()
mean_height = df['Height_(cm)'].mean()

print("Height")
print(f"Minimum height: {min_height}")
print(f"Maximum height: {max_height}")
print(f"Mean height: {mean_height}")

#2 Weight discriptive statistics
min_weight = df['Weight_(kg)'].min()
max_weight = df['Weight_(kg)'].max()
mean_weight = df['Weight_(kg)'].mean()

print('\nWeight')
print(f"Minimum weight: {min_weight}")
print(f"Maximum weight: {max_weight}")
print(f"Mean weight: {mean_weight}")

#3 BMI discriptive statistics
min_BMI = df['BMI'].min()
max_BMI = df['BMI'].max()
mean_BMI = df['BMI'].mean()

print('\nBMI')
print(f"Minimum BMI: {min_BMI}")
print(f"Maximum BMI: {max_BMI}")
print(f"Mean BMI: {mean_BMI}")

Height
Minimum height: 91.0
Maximum height: 241.0
Mean height: 170.61527453100817

Weight
Minimum weight: 24.95
Maximum weight: 293.02
Mean weight: 83.5888045600391

BMI
Minimum BMI: 12.02
Maximum BMI: 99.33
Mean BMI: 28.626270677178617

- Report the number of column names, null values, and their data types

In [99]:
# 1. Number of column names
num_columns = len(df.columns)
print(f"Number of column names: {num_columns}")

# 2. Null values (NaN) in each column
null_values_per_column = df.isnull().sum()
print("\nNull values per column:")
print(null_values_per_column)

# 3. Data types of each column
column_data_types = df.dtypes
print("\nData types per column:")
print(column_data_types)

Number of column names: 19

Null values per column:
General_Health                  0
Checkup                         0
Exercise                        0
Heart_Disease                   0
Skin_Cancer                     0
Other_Cancer                    0
Depression                      0
Diabetes                        0
Arthritis                       0
Sex                             0
Age_Category                    0
Height_(cm)                     3
Weight_(kg)                     0
BMI                             2
Smoking_History                 0
Alcohol_Consumption             0
Fruit_Consumption               0
Green_Vegetables_Consumption    0
FriedPotato_Consumption         0
dtype: int64

Data types per column:
General_Health                   object
Checkup                          object
Exercise                         object
Heart_Disease                    object
Skin_Cancer                      object
Other_Cancer                     object
Depression                       object
Diabetes                         object
Arthritis                        object
Sex                              object
Age_Category                     object
Height_(cm)                     float64
Weight_(kg)                     float64
BMI                             float64
Smoking_History                  object
Alcohol_Consumption               int64
Fruit_Consumption                 int64
Green_Vegetables_Consumption      int64
FriedPotato_Consumption           int64
dtype: object